name: Nexus Legal AI Scraping

on:

  schedule:
    - cron: '0 * * * *'

  workflow_dispatch:

jobs:

  scraping:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

        with:
          python-version: '3.11'

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies

        run: |

          pip install -r requirements.txt

      - name: Run scraping

        env:

          SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
          SUPABASE_DB: ${{ secrets.SUPABASE_DB }}
          SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
          SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          SUPABASE_PORT: ${{ secrets.SUPABASE_PORT }}

          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}

          BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}

        run: |

          python multi_scraping.py